// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module add (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] a;
input  [15:0] b;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln187_fu_269_p2;
reg   [0:0] icmp_ln187_reg_667;
wire   [0:0] icmp_ln188_fu_275_p2;
reg   [0:0] icmp_ln188_reg_671;
reg   [0:0] tmp_reg_675;
reg   [0:0] tmp_30_reg_682;
wire   [15:0] zext_ln191_fu_307_p1;
wire   [15:0] zext_ln192_fu_321_p1;
reg   [15:0] zext_ln192_reg_693;
wire   [13:0] zext_ln198_fu_341_p1;
wire   [13:0] zext_ln199_fu_353_p1;
reg   [13:0] zext_ln199_reg_704;
wire  signed [13:0] sext_ln204_fu_372_p1;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln203_fu_357_p2;
wire   [15:0] expA_3_fu_377_p2;
wire   [15:0] add_ln211_fu_390_p2;
wire   [0:0] icmp_ln207_fu_384_p2;
wire  signed [14:0] sext_ln214_fu_396_p1;
reg  signed [14:0] sext_ln214_reg_730;
wire  signed [13:0] sext_ln215_fu_416_p1;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln214_fu_400_p2;
wire   [15:0] expB_1_fu_421_p2;
wire   [15:0] add_ln222_fu_433_p2;
wire   [0:0] icmp_ln218_fu_427_p2;
wire   [27:0] zext_ln236_fu_509_p1;
reg   [0:0] tmp_34_reg_763;
wire   [27:0] zext_ln246_fu_547_p1;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln245_fu_531_p2;
wire   [15:0] expA_6_fu_552_p2;
wire   [15:0] add_ln253_fu_565_p2;
wire   [0:0] icmp_ln249_fu_559_p2;
wire   [31:0] resultMantissa_7_fu_571_p1;
wire   [31:0] resultMantissa_8_fu_591_p2;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln256_fu_585_p2;
wire   [15:0] expA_7_fu_598_p2;
wire   [15:0] add_ln264_fu_611_p2;
wire   [0:0] icmp_ln260_fu_605_p2;
reg   [13:0] mantissaA_0_reg_68;
reg   [15:0] expA_0_reg_77;
reg   [15:0] i_loop_reg_86;
reg   [13:0] ap_phi_mux_mantissaA_1_phi_fu_100_p4;
reg   [15:0] expA_1_reg_107;
reg   [13:0] mantissaB_0_reg_118;
reg   [15:0] expB_0_reg_127;
reg   [15:0] i_loop_1_reg_136;
reg   [13:0] ap_phi_mux_mantissaB_1_phi_fu_150_p4;
reg   [15:0] expA_2_reg_157;
reg   [15:0] i_loop_2_reg_167;
reg   [27:0] resultMantissa_3_reg_178;
reg   [15:0] ap_phi_mux_expA_4_ph_phi_fu_190_p4;
reg   [27:0] ap_phi_mux_resultMantissa_5_ph_s_phi_fu_201_p4;
reg   [15:0] expA_4_reg_208;
reg   [15:0] i_loop_3_reg_218;
reg   [31:0] resultMantissa_5_reg_229;
reg   [15:0] ap_phi_mux_expA_5_phi_fu_241_p4;
reg   [31:0] ap_phi_mux_resultMantissa_6_phi_fu_251_p4;
wire   [15:0] result_2_fu_648_p3;
reg   [15:0] ap_phi_mux_p_0_phi_fu_261_p6;
reg   [15:0] p_0_reg_258;
wire   [4:0] expA_fu_297_p4;
wire   [4:0] expB_fu_311_p4;
wire   [9:0] mantissaA_fu_325_p1;
wire   [10:0] mantissaA_2_fu_333_p3;
wire   [9:0] mantissaB_fu_329_p1;
wire   [10:0] mantissaB_2_fu_345_p3;
wire   [12:0] tmp_31_fu_362_p4;
wire   [12:0] tmp_32_fu_406_p4;
wire  signed [14:0] sext_ln226_fu_439_p1;
wire   [0:0] xor_ln226_fu_443_p2;
wire   [14:0] resultMantissa_1_fu_457_p2;
wire   [14:0] add_ln227_fu_447_p2;
wire   [0:0] and_ln189_fu_470_p2;
wire   [14:0] resultMantissa_fu_452_p2;
wire   [14:0] resultMantissa_2_fu_462_p3;
wire  signed [14:0] resultMantissa_4_fu_475_p3;
wire  signed [15:0] sext_ln189_fu_483_p1;
wire   [0:0] tmp_33_fu_487_p3;
wire   [15:0] sub_ln238_fu_495_p2;
wire   [15:0] select_ln236_fu_501_p3;
wire   [16:0] tmp_35_fu_521_p4;
wire   [26:0] tmp_36_fu_537_p4;
wire   [21:0] tmp_37_fu_575_p4;
wire   [5:0] trunc_ln267_1_fu_621_p1;
wire   [9:0] trunc_ln267_fu_617_p1;
wire   [0:0] and_ln268_fu_633_p2;
wire   [15:0] result_fu_625_p3;
wire   [0:0] or_ln268_fu_637_p2;
wire   [15:0] result_1_fu_642_p2;
reg   [15:0] ap_return_preg;
reg   [4:0] ap_NS_fsm;
reg    ap_condition_430;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_return_preg = 16'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 16'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln187_reg_667 == 1'd1) | ((icmp_ln188_reg_671 == 1'd1) | ((icmp_ln260_fu_605_p2 == 1'd1) | (icmp_ln256_fu_585_p2 == 1'd0)))))) begin
            ap_return_preg <= ap_phi_mux_p_0_phi_fu_261_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln203_fu_357_p2 == 1'd1) & (icmp_ln207_fu_384_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        expA_0_reg_77 <= expA_3_fu_377_p2;
    end else if (((icmp_ln188_fu_275_p2 == 1'd0) & (icmp_ln187_fu_269_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        expA_0_reg_77 <= zext_ln191_fu_307_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if (((icmp_ln207_fu_384_p2 == 1'd1) & (icmp_ln203_fu_357_p2 == 1'd1))) begin
            expA_1_reg_107 <= expA_3_fu_377_p2;
        end else if ((icmp_ln203_fu_357_p2 == 1'd0)) begin
            expA_1_reg_107 <= expA_0_reg_77;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln249_fu_559_p2 == 1'd0) & (icmp_ln245_fu_531_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        expA_2_reg_157 <= expA_6_fu_552_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln218_fu_427_p2 == 1'd1) | (icmp_ln214_fu_400_p2 == 1'd0)))) begin
        expA_2_reg_157 <= expA_1_reg_107;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln249_fu_559_p2 == 1'd1) | (icmp_ln245_fu_531_p2 == 1'd1)))) begin
        expA_4_reg_208 <= ap_phi_mux_expA_4_ph_phi_fu_190_p4;
    end else if (((icmp_ln256_fu_585_p2 == 1'd1) & (icmp_ln260_fu_605_p2 == 1'd0) & (icmp_ln188_reg_671 == 1'd0) & (icmp_ln187_reg_667 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        expA_4_reg_208 <= expA_7_fu_598_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln214_fu_400_p2 == 1'd1) & (icmp_ln218_fu_427_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        expB_0_reg_127 <= expB_1_fu_421_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln207_fu_384_p2 == 1'd1) | (icmp_ln203_fu_357_p2 == 1'd0)))) begin
        expB_0_reg_127 <= zext_ln192_reg_693;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln214_fu_400_p2 == 1'd1) & (icmp_ln218_fu_427_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_loop_1_reg_136 <= add_ln222_fu_433_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln207_fu_384_p2 == 1'd1) | (icmp_ln203_fu_357_p2 == 1'd0)))) begin
        i_loop_1_reg_136 <= 16'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln249_fu_559_p2 == 1'd0) & (icmp_ln245_fu_531_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        i_loop_2_reg_167 <= add_ln253_fu_565_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln218_fu_427_p2 == 1'd1) | (icmp_ln214_fu_400_p2 == 1'd0)))) begin
        i_loop_2_reg_167 <= 16'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln249_fu_559_p2 == 1'd1) | (icmp_ln245_fu_531_p2 == 1'd1)))) begin
        i_loop_3_reg_218 <= 16'd1;
    end else if (((icmp_ln256_fu_585_p2 == 1'd1) & (icmp_ln260_fu_605_p2 == 1'd0) & (icmp_ln188_reg_671 == 1'd0) & (icmp_ln187_reg_667 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        i_loop_3_reg_218 <= add_ln264_fu_611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln203_fu_357_p2 == 1'd1) & (icmp_ln207_fu_384_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_loop_reg_86 <= add_ln211_fu_390_p2;
    end else if (((icmp_ln188_fu_275_p2 == 1'd0) & (icmp_ln187_fu_269_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_loop_reg_86 <= 16'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln203_fu_357_p2 == 1'd1) & (icmp_ln207_fu_384_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mantissaA_0_reg_68 <= sext_ln204_fu_372_p1;
    end else if (((icmp_ln188_fu_275_p2 == 1'd0) & (icmp_ln187_fu_269_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mantissaA_0_reg_68 <= zext_ln198_fu_341_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln214_fu_400_p2 == 1'd1) & (icmp_ln218_fu_427_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        mantissaB_0_reg_118 <= sext_ln215_fu_416_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln207_fu_384_p2 == 1'd1) | (icmp_ln203_fu_357_p2 == 1'd0)))) begin
        mantissaB_0_reg_118 <= zext_ln199_reg_704;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln188_fu_275_p2 == 1'd1) & (icmp_ln187_fu_269_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_258 <= a;
    end else if (((icmp_ln187_fu_269_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_258 <= b;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((icmp_ln260_fu_605_p2 == 1'd1) & (icmp_ln188_reg_671 == 1'd0) & (icmp_ln187_reg_667 == 1'd0)) | ((icmp_ln256_fu_585_p2 == 1'd0) & (icmp_ln188_reg_671 == 1'd0) & (icmp_ln187_reg_667 == 1'd0))))) begin
        p_0_reg_258 <= result_2_fu_648_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln249_fu_559_p2 == 1'd0) & (icmp_ln245_fu_531_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                resultMantissa_3_reg_178[15 : 0] <= zext_ln246_fu_547_p1[15 : 0];
    end else if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln218_fu_427_p2 == 1'd1) | (icmp_ln214_fu_400_p2 == 1'd0)))) begin
                resultMantissa_3_reg_178[15 : 0] <= zext_ln236_fu_509_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln249_fu_559_p2 == 1'd1) | (icmp_ln245_fu_531_p2 == 1'd1)))) begin
        resultMantissa_5_reg_229 <= resultMantissa_7_fu_571_p1;
    end else if (((icmp_ln256_fu_585_p2 == 1'd1) & (icmp_ln260_fu_605_p2 == 1'd0) & (icmp_ln188_reg_671 == 1'd0) & (icmp_ln187_reg_667 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        resultMantissa_5_reg_229 <= resultMantissa_8_fu_591_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        icmp_ln187_reg_667 <= icmp_ln187_fu_269_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln187_fu_269_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        icmp_ln188_reg_671 <= icmp_ln188_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln207_fu_384_p2 == 1'd1) | (icmp_ln203_fu_357_p2 == 1'd0)))) begin
        sext_ln214_reg_730 <= sext_ln214_fu_396_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln188_fu_275_p2 == 1'd0) & (icmp_ln187_fu_269_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_30_reg_682 <= b[32'd15];
        tmp_reg_675 <= a[32'd15];
        zext_ln192_reg_693[4 : 0] <= zext_ln192_fu_321_p1[4 : 0];
        zext_ln199_reg_704[9 : 0] <= zext_ln199_fu_353_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln218_fu_427_p2 == 1'd1) | (icmp_ln214_fu_400_p2 == 1'd0)))) begin
        tmp_34_reg_763 <= resultMantissa_4_fu_475_p3[32'd14];
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state5) & ((icmp_ln187_reg_667 == 1'd1) | ((icmp_ln188_reg_671 == 1'd1) | ((icmp_ln260_fu_605_p2 == 1'd1) | (icmp_ln256_fu_585_p2 == 1'd0))))) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((icmp_ln249_fu_559_p2 == 1'd1) & (icmp_ln245_fu_531_p2 == 1'd0))) begin
            ap_phi_mux_expA_4_ph_phi_fu_190_p4 = expA_6_fu_552_p2;
        end else if ((icmp_ln245_fu_531_p2 == 1'd1)) begin
            ap_phi_mux_expA_4_ph_phi_fu_190_p4 = expA_2_reg_157;
        end else begin
            ap_phi_mux_expA_4_ph_phi_fu_190_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_expA_4_ph_phi_fu_190_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_430)) begin
        if (((icmp_ln260_fu_605_p2 == 1'd1) & (icmp_ln256_fu_585_p2 == 1'd1))) begin
            ap_phi_mux_expA_5_phi_fu_241_p4 = expA_7_fu_598_p2;
        end else if ((icmp_ln256_fu_585_p2 == 1'd0)) begin
            ap_phi_mux_expA_5_phi_fu_241_p4 = expA_4_reg_208;
        end else begin
            ap_phi_mux_expA_5_phi_fu_241_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_expA_5_phi_fu_241_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if (((icmp_ln207_fu_384_p2 == 1'd1) & (icmp_ln203_fu_357_p2 == 1'd1))) begin
            ap_phi_mux_mantissaA_1_phi_fu_100_p4 = sext_ln204_fu_372_p1;
        end else if ((icmp_ln203_fu_357_p2 == 1'd0)) begin
            ap_phi_mux_mantissaA_1_phi_fu_100_p4 = mantissaA_0_reg_68;
        end else begin
            ap_phi_mux_mantissaA_1_phi_fu_100_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_mantissaA_1_phi_fu_100_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((icmp_ln218_fu_427_p2 == 1'd1) & (icmp_ln214_fu_400_p2 == 1'd1))) begin
            ap_phi_mux_mantissaB_1_phi_fu_150_p4 = sext_ln215_fu_416_p1;
        end else if ((icmp_ln214_fu_400_p2 == 1'd0)) begin
            ap_phi_mux_mantissaB_1_phi_fu_150_p4 = mantissaB_0_reg_118;
        end else begin
            ap_phi_mux_mantissaB_1_phi_fu_150_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_mantissaB_1_phi_fu_150_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (((icmp_ln260_fu_605_p2 == 1'd1) & (icmp_ln188_reg_671 == 1'd0) & (icmp_ln187_reg_667 == 1'd0)) | ((icmp_ln256_fu_585_p2 == 1'd0) & (icmp_ln188_reg_671 == 1'd0) & (icmp_ln187_reg_667 == 1'd0))))) begin
        ap_phi_mux_p_0_phi_fu_261_p6 = result_2_fu_648_p3;
    end else begin
        ap_phi_mux_p_0_phi_fu_261_p6 = p_0_reg_258;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((icmp_ln249_fu_559_p2 == 1'd1) & (icmp_ln245_fu_531_p2 == 1'd0))) begin
            ap_phi_mux_resultMantissa_5_ph_s_phi_fu_201_p4 = zext_ln246_fu_547_p1;
        end else if ((icmp_ln245_fu_531_p2 == 1'd1)) begin
            ap_phi_mux_resultMantissa_5_ph_s_phi_fu_201_p4 = resultMantissa_3_reg_178;
        end else begin
            ap_phi_mux_resultMantissa_5_ph_s_phi_fu_201_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_resultMantissa_5_ph_s_phi_fu_201_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_430)) begin
        if (((icmp_ln260_fu_605_p2 == 1'd1) & (icmp_ln256_fu_585_p2 == 1'd1))) begin
            ap_phi_mux_resultMantissa_6_phi_fu_251_p4 = resultMantissa_8_fu_591_p2;
        end else if ((icmp_ln256_fu_585_p2 == 1'd0)) begin
            ap_phi_mux_resultMantissa_6_phi_fu_251_p4 = resultMantissa_5_reg_229;
        end else begin
            ap_phi_mux_resultMantissa_6_phi_fu_251_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_resultMantissa_6_phi_fu_251_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln187_reg_667 == 1'd1) | ((icmp_ln188_reg_671 == 1'd1) | ((icmp_ln260_fu_605_p2 == 1'd1) | (icmp_ln256_fu_585_p2 == 1'd0)))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln187_reg_667 == 1'd1) | ((icmp_ln188_reg_671 == 1'd1) | ((icmp_ln260_fu_605_p2 == 1'd1) | (icmp_ln256_fu_585_p2 == 1'd0)))))) begin
        ap_return = ap_phi_mux_p_0_phi_fu_261_p6;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln188_fu_275_p2 == 1'd0) & (icmp_ln187_fu_269_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((icmp_ln188_fu_275_p2 == 1'd1) | (icmp_ln187_fu_269_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln207_fu_384_p2 == 1'd1) | (icmp_ln203_fu_357_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln218_fu_427_p2 == 1'd1) | (icmp_ln214_fu_400_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln249_fu_559_p2 == 1'd1) | (icmp_ln245_fu_531_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln187_reg_667 == 1'd1) | ((icmp_ln188_reg_671 == 1'd1) | ((icmp_ln260_fu_605_p2 == 1'd1) | (icmp_ln256_fu_585_p2 == 1'd0)))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln211_fu_390_p2 = (i_loop_reg_86 + 16'd1);

assign add_ln222_fu_433_p2 = (i_loop_1_reg_136 + 16'd1);

assign add_ln227_fu_447_p2 = ($signed(sext_ln214_reg_730) + $signed(sext_ln226_fu_439_p1));

assign add_ln253_fu_565_p2 = (i_loop_2_reg_167 + 16'd1);

assign add_ln264_fu_611_p2 = (i_loop_3_reg_218 + 16'd1);

assign and_ln189_fu_470_p2 = (xor_ln226_fu_443_p2 & tmp_reg_675);

assign and_ln268_fu_633_p2 = (tmp_reg_675 & tmp_30_reg_682);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_condition_430 = ((icmp_ln188_reg_671 == 1'd0) & (icmp_ln187_reg_667 == 1'd0) & (1'b1 == ap_CS_fsm_state5));
end

assign expA_3_fu_377_p2 = (expA_0_reg_77 + 16'd1);

assign expA_6_fu_552_p2 = (expA_2_reg_157 + 16'd1);

assign expA_7_fu_598_p2 = ($signed(16'd65535) + $signed(expA_4_reg_208));

assign expA_fu_297_p4 = {{a[14:10]}};

assign expB_1_fu_421_p2 = (expB_0_reg_127 + 16'd1);

assign expB_fu_311_p4 = {{b[14:10]}};

assign icmp_ln187_fu_269_p2 = ((a == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln188_fu_275_p2 = ((b == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln203_fu_357_p2 = (($signed(expA_0_reg_77) < $signed(zext_ln192_reg_693)) ? 1'b1 : 1'b0);

assign icmp_ln207_fu_384_p2 = (($signed(i_loop_reg_86) > $signed(16'd25)) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_400_p2 = (($signed(expB_0_reg_127) < $signed(expA_1_reg_107)) ? 1'b1 : 1'b0);

assign icmp_ln218_fu_427_p2 = (($signed(i_loop_1_reg_136) > $signed(16'd25)) ? 1'b1 : 1'b0);

assign icmp_ln245_fu_531_p2 = ((tmp_35_fu_521_p4 == 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_559_p2 = (($signed(i_loop_2_reg_167) > $signed(16'd25)) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_585_p2 = (($signed(tmp_37_fu_575_p4) < $signed(22'd1)) ? 1'b1 : 1'b0);

assign icmp_ln260_fu_605_p2 = (($signed(i_loop_3_reg_218) > $signed(16'd25)) ? 1'b1 : 1'b0);

assign mantissaA_2_fu_333_p3 = {{1'd1}, {mantissaA_fu_325_p1}};

assign mantissaA_fu_325_p1 = a[9:0];

assign mantissaB_2_fu_345_p3 = {{1'd1}, {mantissaB_fu_329_p1}};

assign mantissaB_fu_329_p1 = b[9:0];

assign or_ln268_fu_637_p2 = (tmp_34_reg_763 | and_ln268_fu_633_p2);

assign resultMantissa_1_fu_457_p2 = ($signed(sext_ln214_reg_730) - $signed(sext_ln226_fu_439_p1));

assign resultMantissa_2_fu_462_p3 = ((xor_ln226_fu_443_p2[0:0] === 1'b1) ? resultMantissa_1_fu_457_p2 : add_ln227_fu_447_p2);

assign resultMantissa_4_fu_475_p3 = ((and_ln189_fu_470_p2[0:0] === 1'b1) ? resultMantissa_fu_452_p2 : resultMantissa_2_fu_462_p3);

assign resultMantissa_7_fu_571_p1 = ap_phi_mux_resultMantissa_5_ph_s_phi_fu_201_p4;

assign resultMantissa_8_fu_591_p2 = resultMantissa_5_reg_229 << 32'd1;

assign resultMantissa_fu_452_p2 = ($signed(sext_ln226_fu_439_p1) - $signed(sext_ln214_reg_730));

assign result_1_fu_642_p2 = (result_fu_625_p3 | 16'd32768);

assign result_2_fu_648_p3 = ((or_ln268_fu_637_p2[0:0] === 1'b1) ? result_1_fu_642_p2 : result_fu_625_p3);

assign result_fu_625_p3 = {{trunc_ln267_1_fu_621_p1}, {trunc_ln267_fu_617_p1}};

assign select_ln236_fu_501_p3 = ((tmp_33_fu_487_p3[0:0] === 1'b1) ? sub_ln238_fu_495_p2 : sext_ln189_fu_483_p1);

assign sext_ln189_fu_483_p1 = resultMantissa_4_fu_475_p3;

assign sext_ln204_fu_372_p1 = $signed(tmp_31_fu_362_p4);

assign sext_ln214_fu_396_p1 = $signed(ap_phi_mux_mantissaA_1_phi_fu_100_p4);

assign sext_ln215_fu_416_p1 = $signed(tmp_32_fu_406_p4);

assign sext_ln226_fu_439_p1 = $signed(ap_phi_mux_mantissaB_1_phi_fu_150_p4);

assign sub_ln238_fu_495_p2 = ($signed(16'd0) - $signed(sext_ln189_fu_483_p1));

assign tmp_31_fu_362_p4 = {{mantissaA_0_reg_68[13:1]}};

assign tmp_32_fu_406_p4 = {{mantissaB_0_reg_118[13:1]}};

assign tmp_33_fu_487_p3 = resultMantissa_4_fu_475_p3[32'd14];

assign tmp_35_fu_521_p4 = {{resultMantissa_3_reg_178[27:11]}};

assign tmp_36_fu_537_p4 = {{resultMantissa_3_reg_178[27:1]}};

assign tmp_37_fu_575_p4 = {{resultMantissa_5_reg_229[31:10]}};

assign trunc_ln267_1_fu_621_p1 = ap_phi_mux_expA_5_phi_fu_241_p4[5:0];

assign trunc_ln267_fu_617_p1 = ap_phi_mux_resultMantissa_6_phi_fu_251_p4[9:0];

assign xor_ln226_fu_443_p2 = (tmp_reg_675 ^ tmp_30_reg_682);

assign zext_ln191_fu_307_p1 = expA_fu_297_p4;

assign zext_ln192_fu_321_p1 = expB_fu_311_p4;

assign zext_ln198_fu_341_p1 = mantissaA_2_fu_333_p3;

assign zext_ln199_fu_353_p1 = mantissaB_2_fu_345_p3;

assign zext_ln236_fu_509_p1 = select_ln236_fu_501_p3;

assign zext_ln246_fu_547_p1 = tmp_36_fu_537_p4;

always @ (posedge ap_clk) begin
    zext_ln192_reg_693[15:5] <= 11'b00000000000;
    zext_ln199_reg_704[13:10] <= 4'b0001;
    resultMantissa_3_reg_178[27:16] <= 12'b000000000000;
end

endmodule //add
